### PR TITLE
Added extra language support(Java, Python) and enabled other languages to be used through default language settings

### PR DESCRIPTION
**Pull request by Helios113**
Hello,

I added support for Java and Python. Also, I enabled users to use any language that is supported by godbolt.org through the default(what we use if the language is unknown) language support. Syntax highlighting only works for C/C++.

### CODE REVIEW

**Comment by MRobertEvers** [comment]
image

Checked it out and it looks good!

**Comment by Helios113** [comment]
@MRobertEvers Hey, I would like to add support for syntax highlighting for the two new languages. Do you know how I can approach this issue?

**Comment by MRobertEvers** [comment]
@Helios113 Sure, on the VSCode side, it's fairly straight-forward, just create the "Ranges" that you want colored in your document and pass them to the editor. See here https://github.com/MRobertEvers/vscode-compiler-explorer/blob/master/src/assembler-syntax-highlight.ts. Basically, just specify the start character index in your document and the end character index, then specify a color. 

Right now, the assembler syntax highlighting is my handrolled quick and dirty highlighter. It just looks for keywords to see if they should be highlighted. If you're up for a more sophisticated approach, you might want to look at how the compiler explorer does it. When I originally made this, I couldn't find where compiler explorer did the syntax highlighting for the assembly, however, I could find where they did the [line highlighting](https://github.com/compiler-explorer/compiler-explorer/blob/main/static/line-colouring.ts). I think that they might be using some syntax highlighting provided by the Monaco Editor, but I'm not sure. I will take a quick look again, and comment if I can find how they do it.

**Comment by MRobertEvers** [comment]
I'm fairly confident the syntax highlighting is done by the Monaco Editor. This is apparently the same editor that powers VSCode, https://github.com/microsoft/monaco-editor.git. But without digging too deep, I don't see where they're performing the syntax highlighting for assembly.

**Comment by Helios113** [comment]
@MRobertEvers Ok, I will have do some digging too then. It should be doable. I'll keep you posted. 

Also are you aware of how to add extra language support to godbolt directly. I was looking at a lecture that examined how java can be compiled to machine code. It would be a nice comparison if one could see how functionally the same code compiles to different machine code on let's say java and c++.

**Comment by MRobertEvers** [comment]
@Helios113 I kept looking, I think the ASM syntax highlighting is handled by a regex parser https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/asm-parser.js. I believe the output of that class is used to syntax highlight, so maybe you could track that down.

To answer your question, look at [Adding a new language](https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingALanguage.md). I haven't added a language myself, but I have added a compiler. The docs are fairly decent, but you'll probably need to do some hacking. 

For your specific example, I'm sorry I don't know much about Java. Although, if you can compile it to machine code, you can use GCC's `objdump` to get the disassembly, which you can then compare to the C++ disassembly. There is a similar tool for MSVC on Windows, but I can't remember it off the top of my head.

**Pull request merged**
